version: '3.4'

networks:
  dev:
    driver: bridge

services:
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weewsa_financialgamebot_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/Database
      - app_data_big:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data:
  app_data_big: