version: '3.4'

networks:
  dev:
    driver: bridge

services:
  telegram-bot-app:
    image: docker.io/library/telegrambotapp
    depends_on:
      - "app_db"
    container_name: telegrambotapp-services
    ports:
      - "8088:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=weewsa_financialgamebot_db; IntegratedSecurity=true;Pooling=true;
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weewsa_financialgamebot_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/Database
      - app_data_big:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data:
  app_data_big: